### PR TITLE
Added exaltScript

### PR DESCRIPTION
**Pull request by pinmissile**
exaltScript is a general-purpose script that adds utility and automates certain aspects of Exalted 3rd Edition campaigns.

### CODE REVIEW

**Comment by pinmissile** [comment]
Found an error in .json, closing and opening another pull request.

**Comment by shdwjk** [comment]
If it hasn't been pulled, you could likely just commit the fix and push again, rather than going round the pull request flow again. =D

**Comment by pjbehr87** [comment]
To expand a little on what shdwjk said:
Any commits you make to the branch you made the PR from will automatically be updated to the PR. You don't have to close and re-open a PR to fix things. Just make commits to the branch and push them to GitHub and you're good to go. You can even confirm this by viewing the PR yourself after you've made the changes.

**Comment by pinmissile** [comment]
Cool, I'll keep that in mind. Still getting the hang of github.

**Comment by shdwjk** [comment]
GitHub takes an already complicated concept of distributed source control and further obscures it behind a gui and convention.  It can be a challenge to get a feeling for how to use it.  I've been using it a long time and I still run into things that are o.O!

**Pull request closed without merging**
