### PR TITLE
Added Charsheet script

### PR DESCRIPTION
**Pull request by GamerGoddessDin**

### CODE REVIEW

**Comment by GamerGoddessDin** [comment]
What do I need to do before this script can be added to the 1-click install system?

**Comment by SteveKoontz** [comment]
This script.json file needs all of the elements that are found on the repo's README.md file

**Comment by GamerGoddessDin** [comment]
What should I do for the elements that have no relevant content. Such as "Conflicts" and "Dependencies"?

**Comment by SteveKoontz** [comment]
You can leave them empty arrays or objects. Check out:
https://raw.githubusercontent.com/Roll20/roll20-api-scripts/master/5th%20Edition%20OGL%20by%20Roll20%20Companion/script.json

**Pull request merged**
