### PR TITLE
[Alien RPG Dice Roller] version 1

### PR DESCRIPTION
**Pull request by dwarfwing**
This is the dice roller for Alien RPG, adding support for the Year Zero Engine push roll mechanics. It is based on the Mutant Year Zero dice roller by The Aaron, with graphics changed to look like the roll template of the Alien RPG sheet and includes base and stress dice. This will also be included as part the character sheet in the upcoming version of it.

### CODE REVIEW

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
@dwarfwing There is a problem with the versioning folder structure of this PR that you will need to fix before we can merge.

To fix, you need to make a copy of your main JS file and put it into a sub-folder that matches the version key/value pair in your script.json. So since you put the version as 1.0, your folder structure will look something like: AlienRPGroller/1.0/AlienRPG.js. Here is a good example of a script with the correct folder structure: https://github.com/Roll20/roll20-api-scripts/tree/master/Ammo

**Comment by dwarfwing** [comment]
Thanks, been looking for further instructions but difficult to find. I had already created a folder for 1.0 but thought it was not needed until the subsequent version. 

I will update and commit new.

**Comment by dwarfwing** [comment]
PR updated with new commit, added the folder structure and standardized version to 1.00 in files and folder naming.

**Review by NicholasR77 — APPROVED** [review]
@dwarfwing - Thanks for making these adjustments! There were a couple of additional changes that needed to made, but I went ahead and fixed them for you. Here's what they were so you know going forward:

1. The key/value pair of the version in the script.json has to match the exact sub-folder name. You set the value to be "1.00", but the sub-folder name was set to be "v1.00". I went ahead and adjusted the key/value pair to match.
2. You had a duplicated script.json file in your sub-folder, which is not necessary. You only need one script.json in the root. 

I appreciate the feedback you had here! I'll take it to the team to see if we can create some updated documentation or update the readme.

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
@dwarfwing - OK just kidding this still failed validation. I guess it doesn't like the "v" in your sub-folder name. So to fix it, go ahead and rename your sub-folder to just "1.00" and then adjust the version key in your script.json to be "1.00". That should do it.

**Comment by dwarfwing** [comment]
I was trying to follow the validation checks to find out what the issue with validating the script.json was. Comparing it to others I changed the way dependencies was listed, a {} instead of [] array. So, I committed that again and hope that will be the final thing. 

I totally missed the v in the version - stare at something for too long and you get blind. Committing again, Thanks for your help.

**Review by NicholasR77 — APPROVED** [review]

**Pull request merged**
