### PR TITLE
WildShape 1.4.1 and WildHelpers 1.3.3

### PR DESCRIPTION
**Pull request by ocangelo**

### CODE REVIEW

**Comment by ocangelo** [comment]
i am not sure i understand what checks are failing, could someone please shed some light?

**Review by dave-roll20 — APPROVED** [review]
In the future please limit pull requests to changing one API script

**Comment by ocangelo** [comment]
There is a dependency between the two, if only WildShape goes through it wouldn't work. Do you still want me to make two separate pull request in that case?

**Comment by ocangelo** [comment]
> In the future please limit pull requests to changing one API script

There is a dependency between the two, if only WildShape goes through it wouldn't work. Do you still want me to make two separate pull request in that case?

**Comment by shdwjk** [comment]
I talked to Nathanael Winget about this, it was a misunderstanding regarding policies of the repo.  He's getting it resolved.

**Comment by ocangelo** [comment]
> I talked to Nathanael Winget about this, it was a misunderstanding regarding policies of the repo. He's getting it resolved.

what is getting resolved?
the files seems to have been merged correctly but i still don't see the updated versions in the one click

**Comment by ocangelo** [comment]
@dave-roll20 @shdwjk i still don't see the updated version in the one click, is there a problem with the script?

**Comment by shdwjk** [comment]
There seems to be some question about what the policy is regarding adding things to the 1-click scripts.  The current best policy from a community standpoint seems to be to very explicitly ask that scripts be included in the 1-click.  It's probably most expedient to open a new pull request (maybe just change the documentation in `script.json` slightly) that is explicitly requesting inclusion in the 1-click installs.

**Comment by ocangelo** [comment]
@shdwjk the scripts were already included in the one click, these are just updated versions for both of them

**Comment by shdwjk** [comment]
Ah.  If you import the script instead of installing it, do you get the right version?

**Comment by ocangelo** [comment]
@shdwjk i am not sure what you mean with that, do you mean installing it manually?

**Comment by shdwjk** [comment]
Ah, I meant "Add Script" and "Import".   I just tried installing WildShape and I get the same results.  I see 1.4.1 in the repo when I pull it down, but I can't get 1.4.1 installed, only 1.4.0.  This is something that Roll20 has to fix with their deploy to the API server.  I pointed this out on another channel, so it's something they are aware of.  Hopefully it will get worked out soon.

**Comment by ocangelo** [comment]
thank you, is that something i can follow somewhere else?

**Comment by shdwjk** [comment]
Not really.

**Comment by ocangelo** [comment]
@dave-roll20 not sure what's happening but now if i look at the drop down for WildShape it shows 1.4.1 in the list but it doesn't have 1.4.0 anymore.
Also if you run the game with either latest or even 1.4.1 selected i can see from my API menu that is still running 1.4.0, so i am guessing something is going bad with the mapping?
WildHelpers is having the same issue

**Comment by ocangelo** [comment]
@dave-roll20 tagging you once more, let me know if there is anything i can do

**Comment by ocangelo** [comment]
i fixed a crash in the API and created another pull request https://github.com/Roll20/roll20-api-scripts/pull/1243

Can someone please look into this?
@shdwjk @dave-roll20

**Pull request merged**
