### PR TITLE
Adding FFG-SWRPG-Dice-Roller

### PR DESCRIPTION
**Pull request by KnowledgeRhino**
Fantasy Flight Games Dice Roller (Update to EotE-Dice.js) for use with
the Star Wars: FFG - API-Compatible Character Sheet.

### CODE REVIEW

**Comment by SteveKoontz** [comment]
How does these scripts differ from those in the EotE Dice Roller folder?

**Comment by KnowledgeRhino** [comment]
A few ways,
- I have run code analysis and fixed code errors
- I had to change the display of several rolls to allow the Roll Template method I use on the associated character sheet to work, also the code that parses the rolls for the Roll Templates is included in the new version.
- I added an auto sheet creator that was provided by a user on Reddit.
- The name scheme of EotE lead to confusion due to the multiple lines, the new name scheme fits the system.
- The authors of the previous work left the project to "anyone" back in august of 2015, and I wanted to distinguish this as different so I didn't have to "re-fix" issues that have already been solved.

**Comment by SteveKoontz** [comment]
Your new sheet is incompatible with the old one, and this new script is as well with the old sheet?

**Comment by KnowledgeRhino** [comment]
The newest version posted on the other GitHub is 100% compatible with the old sheet. I added the old vehicle sections to a separate tab so it will import the data 100% correctly. Please see the pull request for version 4.0.4.2.

As to the other question it is answered both in my previous comment and in the package.json. The FFG-SWRPG-API-Compatible.js is not at all compatible with the EotE-Dice.js
- The old sheet was not setup for Roll Templates and the display would be very ugly and might not display at all.

Additionally if someone uses the Old API-Compatible Character sheet with the new script, it will fail.
- As stated above, the Roll Template changes would break the core roll functionality.

FFG-SWRPG-API-Compatible.js is the companion script for the new changed sheet. I matched the script name to the Sheet Name. If the former sheet author wants to support his stuff again and continue, he can, this is a "fork" project. At the same time many people have requested features to go into the changes I made. I am willing to continue this as a Custom sheet/script but the community responding on the thread seem to appreciate the changes since the old sheet was abandoned.

**Comment by SteveKoontz** [comment]
I just wanted to verify with you that the previous versions you have here 2.6, 3.0 are the old versions that are compatible with the previous version of the character sheet?

**Comment by KnowledgeRhino** [comment]
2.6 + 3.0 Work with the Edge of the Empire - API Compatible Sheet.
4.0 and later work with the FFG API Compatible sheet.

4.0.4.X introduced Roll Templates in the HTML/CSS/JavaScript, due to the changes if you do not have all of them at least on 4.0.4.1 they will not work or will display blank rolls.

I wanted to list it as a separate script, hence the name change. This script will work in conjunction with the new character sheet, which should be approved soon.

**Pull request closed without merging**
