### PR TITLE
One-Click fix: It's A Trap themes

### PR DESCRIPTION
**Pull request by Cazra**
Renamed It's A Trap theme folders to match latest version.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @Cazra 

Can you run me through what the intention is here? When doing versioning in the APIs the process is to make a new folder for each version rather than renaming the old ones. This prevents breaking the script for people on the old version.

Thanks,
Cassie

**Comment by Cazra** [comment]
The renamed folders are for patched versions, where the minor version was broken. E.g. 3.1 was broken, and 3.1.1 is patched so that it is no longer broken.

It would have been broken for players using the unpatched minor version for the patch anyways.

**Comment by Cazra** [comment]
To clarify: In the last pull request for the trap themes, I updated the script.json files' version numbers, but forgot to bump up the patch version of the minor version's folders. This caused all the trap theme scripts to break. In this pull request, renaming the minor versions' folders so that their patch number is bumped up to match the version in the script.json files fixes this error.

**Comment by Cazra** [comment]
If it's a big deal, I'll just add the old version folders back in with a deprecated version of the script...

**Comment by Cazra** [comment]
hello?

**Comment by clevett** [comment]
Greetings Cazra,

Thanks for the detailed explantation. I'll check to see if we have a planned restart this week that I can include this update in. With the American holiday on July 4th, it unfortunately may need to wait till Tuesday.

- Cassie

**Comment by Cazra** [comment]
Okay, thanks for getting back to me. In the meantime, I've posted a workaround in the forums for the users who are experiencing problems with the script. Happy 4th!

**Pull request merged**
