### PR TITLE
BladesCompanion 2.3

### PR DESCRIPTION
**Pull request by joesinghaus**
- fixed a bug concerning image size versions
- improved formatting

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hey @joesinghaus --
It looks like removing the query strings from the image URLs is breaking the script.  I don't know if doing that was related to image size versions, but you should restore a query to the end of the URL, because AWS refuses to serve the image without a query (`"ERROR: You must include the query string in your URL. For example, use 'https://s3.amazonaws.com/files.staging.d20.io/images/123456/med.png?12345678', not 'https://s3.amazonaws.com/files.staging.d20.io/images/123456/med.png'"`).  You should be able to add basically any number to it and it will work fine (tested myself and it kept working).

Just a heads-up.  Probably best to go ahead and just modify it within the same version, since this one breaks on a lot of its core functionality.

Jeff

**Comment by joesinghaus** [comment]
Yeah, I just noticed in my game as well, thanks for the heads-up.
Last-minute breaking change -.-. I'll revert it asap.

**Comment by joesinghaus** [comment]
#670 created which reverts this.

**Comment by joesinghaus** [comment]
By the way Jeff, you're playing a Blades game? GMing one? :)

**Comment by Solarswordsman** [comment]
Well, not currently, though I'm a big fan of the game (and your sheet/script!).  I occasionally fiddle around with it, but actually my fiancee was the one who noticed the bug (she fiddles more :) ).  I expect I'll probably play it sometime again soon (currently playing The Veil), or perhaps one of the Forged in the Dark games that are all publishing now.

**Pull request merged**
