### PR TITLE
[Combat Master] v.2.34: fix one-click install + new version

### PR DESCRIPTION
**Pull request by Anduh**
* update script to 2.34, from script author @vicberg's [repo](https://github.com/vicberg/CombatMaster)
* **v.2.34:**  numerous fixes surrounding targeted spells
* fix issues with files, should make the API work again from install menu(v.2.33 was broken)
* made older versions v.2.33, v.32 and v.2.22 available, like most other API do
* [related forum comment](https://app.roll20.net/forum/permalink/9275779/)

Considering the current install isn't working, nor is the option to select older versions, my update should only be able to make the situation better, even if it isn't guaranteed to work.

### CODE REVIEW

**Comment by Reonin** [comment]
I believe the one click install might be related to the Authors in the array bracket notation when only one author is listed. I'll be on the lookout if your fixes here don't resolve this issue @Anduh

**Comment by Anduh** [comment]
@Reonin the update didn't seem to work, it shows the following error when installed, regardless of what version you try to select:
`No such file or directory @ rb_sysopen - /home/symbly/www/d20-app/apiscripts/CombatMaster/2.33/CombatMaster.js`

I did create that folder and placed that version of the script in it, but the error message shows up even when I try to change it to v.2.22, which in theory shouldn't care if it's some weird thing that happen to be hard-coded into the script in some way.

More discussion and people with this issue can be found in [this forum thread](https://app.roll20.net/forum/permalink/9317469/).

There should also be an open ticket on this made by the scripts author @vicberg .

**Comment by Reonin** [comment]
Yeah, I noticed when the changes hit live this week these cases didn't get resolved. 😞 I believe we will be doing a deeper dive on what's breaking these one clicks but I don't have a firm timeline on when that will be just yet.

**Comment by Anduh** [comment]
I'll submit an update to the script's description to be copy the direct version from Vicberg's repo until things start to work.

**Comment by Anduh** [comment]
Have you checked into this issue at some point? I did submit a PR for a newer version of the API, but that didn't appear to have solved anything either.

**Comment by vicberg** [comment]
It's working now.  I didn't do anything.  Looks like someone did.

**Comment by Anduh** [comment]
Cool, so Roll20 seems to have fixed it, as nobody have updated the Dropdown version since I did last time. Guess I could submit your latest version to Roll20 so the CombatMaster through it is up-to-date.

Or do you wanna try submit and update following the format I did?

**Pull request merged**
