### PR TITLE
Shadowrun 5 specific scripts for glitches and initiative

### PR DESCRIPTION
**Pull request by jflo**
Any tips for best practices on documentation?

### CODE REVIEW

**Comment by shdwjk** [comment]
There is some discussion in the README.md:

> description: A short explanation of the script and it's use that will appear along side the script on Roll20. It is important for this section to be filled out in detail, as it's the primary way users will get information about the purpose and use of the script. Included in the description section needs to be an example use or purpose, list and explanation of API Commands, and any other information necessary to operating the script.

Beyond that, I'd start with a paragraph describing why the script exists and why someone would want to use it, then talk about any commands for it, then talk about any configuration parameters.

**Comment by SteveKoontz** [comment]
There are a few issues. Each script needs to be in it's own folder at the parent level. I know you wanted them to be bundled under a shadowrun folder but our system needs them to be separate. Also your script.json files aren't valid. You can't have returns in your description that aren't encoded. You can use markdown I.E. "\r". Check out the 5e Companion script or TokenMod as examples. Submit a new pull request when you've made these changes so we can get your scripts into the one-click install.

**Comment by jflo** [comment]
So is it better to have multiple top level folders with an SR5 prefix each, or should I combine them all into a single script, under a single directory?

**Comment by SteveKoontz** [comment]
Either is fine. When I did the 5E Companion and 13th Age Companion scripts I combined them and created API commands to toggle off parts of the functionality. But if you think most people will only want parts of the scripts, turning them each into their own is fine as well.

**Pull request closed without merging**
