### PR TITLE
Please add Initiative Tracker Plus to the Roll20 one-click API list.

### PR DESCRIPTION
**Pull request by jaculpiii**
This is a heavily modified version of Ken L's Tracker Jacker that ceased being supported 5 years ago.  I'm not sure if this is the correct way to approach this as I'm not very familiar with github.  Please let me know if I need to do things differently.

### CODE REVIEW

**Review by Anduh — CHANGES_REQUESTED** [review]
Remove the Licence file, all code in this repo is under MIT Licence already, so no additional shouldn't (and probably can't) be added here.

**Comment by jaculpiii** [comment]
Removed the license file.

**Review by Anduh — APPROVED** [review]
Nice. 

I'm curious of what role the macros.json have on the API, haven't seen other APIs that would include a similar file.

**Comment by jaculpiii** [comment]
They are just examples for users that may have VTTES, though I guess they aren't really available on the one-click API so I can remove the file and eventually make them be included in a "Help" handout instead.

**Pull request merged**
