### PR TITLE
Api one click support

### PR DESCRIPTION
**Pull request by Cazra**

### CODE REVIEW

**Comment by SteveKoontz** [comment]
Since the users taking advantage of the one-click install aren't necessarily very tech savvy and won't be accessing the script repo at all, we're making a push to have all the documentation on how to use the script in the description of the package.json. Look at the 5E OGL Companion or the TokenMod script for examples. Can you add your documentation to the package.json?

**Comment by Cazra** [comment]
Sure. I'll just copy the README.md contents into "description" field. It all doesn't look very clean on one line though, which is why I was just referring the user to the README.

**Comment by Cazra** [comment]
Okay, the complete documentation for those scripts is now in their package.json files.

**Comment by SteveKoontz** [comment]
You can format the description to be on multiple lines and have access to markdown formatting.

**Comment by Cazra** [comment]
Oh, JSON validators don't normally like newline characters in field values, so I put it all on one line with escaped carriage return characters. If it would be better to have it broken into multiple lines, I can do that instead.

**Comment by Cazra** [comment]
To clarify, are you meaning to say that this:

```
{
    "name": "Marching Order",
    "script": "marchingOrder.js",
    "version": "2.0",
    "previousversions": [],
    "description": "# Marching Order

    This script allows you to select tokens and tell them to follow each other
    in some specified marching order.

    ### To set one token to follow another

    Select the token that will be the follower.
    In the chat, enter the command !follow [leader name]

    [leader name] is the name of the token the follower token will be
    following. You can use this method consecutively for pairs of leader/follower
    tokens to specify a chain of tokens to be in some marching order.

    ### To specify several tokens making up a marching order

    Arrange the tokens in order from west to east, east to west, south to north,
    or north to south.

    Select all the tokens that will be in the marching order.

    In the chat enter the command !follow [north|east|south|west]

    For !follow north, the northmost token will be the leader in the marching order
    and the southmost token will be the caboose. The same pattern follows for
    the other cardinal directions.

    ### To make tokens stop following each other

    Just manually drag-and-drop the token out of the marching order.
    They will step out of line in the marching order, but the rest of the
    marching order will be unaffected. If a token was following the token
    that stepped out of line, they will instead follow the token that the token
    which stepped out of line was following.
",
    "authors": "Stephen Lindberg",
    "roll20userid": 46544,
    "useroptions": [],
    "dependencies": {},
    "modifies": {
        "left": "read, write",
        "rotation": "read, write",
        "token": "read",
        "top": "read, write"
    },
    "conflicts": []
}
```

is acceptable over this:

```
{
    "name": "Marching Order",
    "script": "marchingOrder.js",
    "version": "2.0",
    "previousversions": [],
    "description": "# Marching Order\r\r This script allows you to select tokens and tell them to follow each other in some specified marching order.\r\r ### To set one token to follow another\r\r Select the token that will be the follower. In the chat, enter the command ```!follow [leader name]``` [leader name] is the name of the token the follower token will be following. You can use this method consecutively for pairs of leader/follower tokens to specify a chain of tokens to be in some marching order.\r\r ### To specify several tokens making up a marching order\r\r Arrange the tokens in order from west to east, east to west, south to north, or north to south. Select all the tokens that will be in the marching order. In the chat enter the command ```!follow [north|east|south|west]``` For !follow north, the northmost token will be the leader in the marching order and the southmost token will be the caboose. The same pattern follows for the other cardinal directions.\r\r ### To make tokens stop following each other Just manually drag-and-drop the token out of the marching order. They will step out of line in the marching order, but the rest of the marching order will be unaffected. If a token was following the token that stepped out of line, they will instead follow the token that the token which stepped out of line was following.",
    "authors": "Stephen Lindberg",
    "roll20userid": 46544,
    "useroptions": [],
    "dependencies": {},
    "modifies": {
        "left": "read, write",
        "rotation": "read, write",
        "token": "read",
        "top": "read, write"
    },
    "conflicts": []
}
```

?

**Comment by Cazra** [comment]
ok, I got those changes in. The descriptions are now multi-line.

**Comment by SteveKoontz** [comment]
Really sorry to have confused you. No, the json structure doesn't support unescaped carriage returns. I meant that our webhost supports the markdown so that you can have escaped "/r" returns in your description.

**Comment by Cazra** [comment]
Yeah, I was a little confused there. Things are fixed back to valid JSON again.

**Comment by SteveKoontz** [comment]
We're making a system change. We're changing the name of the package.json file to script.json. Can you update your files accordingly?

**Comment by Cazra** [comment]
ok. The package.json files have been converted to script.json.

**Pull request merged**
