### PR TITLE
COFantasy: bug fixes and flying creatures grip attack

### PR DESCRIPTION
**Pull request by Ulty**
@clevett : I need your help. I noticed a few weeks ago that this script cannot be added (from Roll20 API library) anymore. It can be imported without any problem, but when using the "Add script" button, the API crashes (error message is `SyntaxError: Invalid or unexpected token`)

I cannot debug that on my own: the error message doesn't help, and I cannot even dichotomy the bug, since everything works fine on my side, and that would require sending tentative some script, let it be installed and look at the results, which only happens once a week, and would prevent users to use the normal version of the script.

The bug seems to trigger with all the versions I tried, by the way. Even the very first ones, which I know used to work.

### CODE REVIEW

**Comment by clevett** [comment]
@Ulty I'll take some time to try to trouble shoot it locally this afternoon. I'll let you know what I find.

**Comment by clevett** [comment]
I was able to add this to a game without trouble. The code will go live in about 4. We can check it one live then.

**Comment by Ulty** [comment]
@clevett : you didn't change anything?

**Comment by Ulty** [comment]
@clevett : I still observe the same issue...

**Pull request merged**
