### PR TITLE
Adding Whisper functionality to character sheet

### PR DESCRIPTION
**Pull request by Kirintale**
The API script and the character sheet have been updated to include whisper functionality.

### CODE REVIEW

**Review by KStomberg — APPROVED** [review]

**Comment by KStomberg** [comment]
Please resolve conflicts in order to merge, thank you.

**Comment by Kirintale** [comment]
Thanks will do this weekend.

**Comment by Kirintale** [comment]
Resolved conflicts.

**Review by KStomberg — APPROVED** [review]

**Comment by KStomberg** [comment]
Perfect, thank you.

**Pull request merged**
