### PR TITLE
RoundMaster API

### PR DESCRIPTION
**Pull request by DameryDad**
This is the first releasable version of RoundMaster, with full documentation, after over 1 year of testing and fixing with a group of 3 DMs and 9 players.  Its purpose is to extend the functionality of the Turn Tracker capability already built in to Roll20.  It is one of several other similar APIs available on the platform that support the Turn Tracker and manage token and character statuses related to the passing of time: the USP of this one is the full richness of its functionality and the degree of user testing that has occurred over a 12 month period.  RoundMaster is based on the much older TrackerJacker API, and many thanks to Ken L. for creating TrackerJacker.  However, roundMaster is a considerable fix and extension to TrackerJacker, suited to many different applications in many different RPG scenarios.  RoundMaster is also the first release as part of the wider RPGMaster series of APIs for Roll20, composed of RoundMaster, CommandMaster, InitiativeMaster, AttackMaster, MagicMaster and MoneyMaster - other than RoundMaster (which is generic) these initially support only the AD&D2e RPG.  On loading, RoundMaster will create handouts in the Campaign with help on all its commands and functions.  It will also create a Character Sheet database of Effect macros - see the documentation in the handouts for more information.

### CODE REVIEW

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
@DameryDad - The PR you have submitted contains non-accepted file types which are proprietary to Microsoft (docx, xlsx). Please remove these files from the PR, or adjust them to be in accepted formats, such as html, markdown, or a plain text file. If you have any questions or concerns, please feel free to let us know. Thank you!

**Comment by DameryDad** [comment]
Have replaced MS file types with RTF and MHT (single file HTML).  I hope this solves the problem.

**Comment by Anduh** [comment]
Is there a reason why you submitted versions v3.004 through v3.019? Seems a bit redundant to do with the initial commit of the API, especially when you have only made v3.020 selectable in the "previous versions" section.

> Have replaced MS file types with RTF and MHT (single file HTML). I hope this solves the problem.

You still have `RoundMaster/v3.020/Effect Documentation.docx` and `RoundMaster/v3.020/RoundMaster Documentation.docx` to change.

**Comment by DameryDad** [comment]
Anduh, sorry I've not done this before.  I had a look at other Roll20 API directories on GitHub and saw lots of older versions and I thought you might need to review the development cycle I'd gone through to get to this point.  As you can see from the version numbering and the change log I've not loaded anything before v3.001 (there are plenty before that!).  This also ensures I have yet another backup for my own purposes, but if you want me to remove them, I'll do so.
I have 4 other APIs nearly ready to post, so I'm using this one as a test to get to know the process.
Also, sorry I forgot I'd put the supporting documents in the v3.020 folder.  I'll just copy over them.

**Comment by DameryDad** [comment]
I've replaced all the MS files now - hope that's OK

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
Hey @DameryDad! Thanks for adjusting those file types, but we do no need to make a few additional changes as well before we can get this merged in.

1. Your subfolder names need to match the `version` key/value pair in your `script.json` and they can't contain letters. So since you've set you the version to be 3.022, your subfolder should look like `RoundMaster/3.022/RoundMaster.js`
2. The js file in your subfolder(s) needs to match the `script` key/value pair in your `script.json` and its case sensitive. So go ahead and rename the script file to be RoundMaster.js, or change the key/value pair instead.
3. Go ahead and adjust the name of your `script.json` file to be all lowercase. I am not sure if the validator cares or not, but let's do it just to be safe.
4. This is optional, but if you want to receive a script author badge on the forums and have your profile linked in the script description, please adjust the `roll20userid` key/value pair in your `script.json` to match the ID of your Roll20 profile. Your ID can be found by click on your name on Roll20, clicking 'My Profile', waiting for it to load, and copy/pasting the ID you see after this part of the URL: https://app.roll20.net/users/

Thanks for your patience as we work through these changes! I'll check back in on this tomorrow morning - let me know if you have any other questions or concerns!

**Comment by DameryDad** [comment]
Thanks for the detailed help - it will be much smoother with the next 4 APIs!  I've made the changes requested, and snuck in the very latest release (just handout avatar & version control changes - no real functionality change).  Happy to take any more comments and make changes as needed.

**Review by NicholasR77 — APPROVED** [review]

**Review by NicholasR77 — APPROVED** [review]

**Comment by NicholasR77** [comment]
@DameryDad OK I did have to make a few minor changes that you might want to look at when you get a chance, but other than that, everything looks good to go now. Thanks for your patience here! Excited to see your script on the site.

**Comment by DameryDad** [comment]
Thanks.  I'll update the Wiki.  Is this going to be loadable by One-Click?

**Pull request merged**
