### PR TITLE
Import HS6e

### PR DESCRIPTION
**Pull request by eepjr24**
Initial add for Hero System 6e character sheet importer.

### CODE REVIEW

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
@eepjr24 Your script needs to be setup with sub-folders of the versions you reference in your script.json. Since you're on version 1.1 right now, you would need a 1.1 subfolder in this script with the current js file in that subfolder. Additionally, since you added 1.0 to the "previousversions" array of your script.json, there needs to be a 1.0 subfolder as well with the 1.0 js file in that subfolder. If you want to see an example of a script that has done this correctly, please see this one: https://github.com/Roll20/roll20-api-scripts/blob/master/Ammo/script.json. Once you fix this, we can go ahead and get this merged in. Thanks!

**Review by NicholasR77 — CHANGES_REQUESTED** [review]
@eepjr24 - I noticed the adjustment to your script.json, but you are still missing sub-folder structure for the script. Please create a version sub-folder called 1.0 in the root of this script folder and copy the most recent version of the Import_HS6e_Roll20.js file into that new sub-folder. After that, I should be able to approve and merge in. Thanks!

**Comment by eepjr24** [comment]
@NicholasR77, I think I finally have the directory structure correct. Please advise.

**Review by NicholasR77 — APPROVED** [review]

**Review by NicholasR77 — APPROVED** [review]

**Comment by NicholasR77** [comment]
@eepjr24 My sincerest apologies for the delay on this! For some reason your messages and the resubmission never appeared in my notifications. I'll talk to our team to make sure something like this doesn't slip through the cracks again. Anyways, you're changes have been merged and you should see the script in the one click dropdown next Tuesday (08/31/2021).

**Pull request merged**
