### PR TITLE
Initiative Tracker Plus v1.28

### PR DESCRIPTION
**Pull request by jaculpiii**
Added playing combat music when the tracker is started/unpaused and reverting to whatever was playing before it was started when it's stopped/paused.

### CODE REVIEW

**Review by Anduh — CHANGES_REQUESTED** [review]
You can't edit the existing files, instead you should add a new folder+file for v1.28, and add v.1.27 to the list of previous versions on the script.json.

**Comment by jaculpiii** [comment]
> You can't edit the existing files, instead you should add a new folder+file for v1.28, and add v.1.27 to the list of previous versions on the script.json.
> 
> #1417 is an example of a correct PR
> 
> (this workflow isn't the same as for character sheets)

Does this mean for any minor fixes/changes I need to create a whole new version or should I only do version changes when it's significant enough to justify a whole new directory?

Thanks,
Chuz

**Comment by jaculpiii** [comment]
@Anduh I think I've made the correct changes, I'll try to remember the proper workflow in the future. Thanks for the heads up.

Chuz

**Review by Anduh — APPROVED** [review]
yeah that looks better.

btw why are you maintaining two copies of the changelog/instructions, both in the script.json & the github readme file? You could just have a hyperlink from the script.json to the readme file...

**Review by NicholasR77 — APPROVED** [review]

**Pull request merged**
