### PR TITLE
One-Click Install update

### PR DESCRIPTION
**Pull request by NathaTerrien**
One-Click Install update

### CODE REVIEW

**Comment by shdwjk** [comment]
`"description": "Enables the use of advance rolls and functions in Natha's Numenera Tabbed character sheets (both english and french) version 4+. Read the [Wiki page)(https://wiki.roll20.net/Script:Numenera_Natha) for help about chat commands and macros.",`

Should be:
`"description": "Enables the use of advance rolls and functions in Natha's Numenera Tabbed character sheets (both english and french) version 4+. Read the [Wiki page](https://wiki.roll20.net/Script:Numenera_Natha) for help about chat commands and macros.",`

The closing `]` on `[Wiki page` was a `)`.

**Comment by NathaTerrien** [comment]
Thanks @shdwjk !

**Comment by SteveKoontz** [comment]
Would it be possible for you to expand the description section of your two scripts. With one-click install the user isn't going to the repo, won't see your help.txt file. Can you move the information necessary to use the script into the description. You can use markdown syntax to format it. Let me know if you have any questions.

**Comment by NathaTerrien** [comment]
@SteveKoontz Concerning the "Porte Monstre Tresors" script, everything's said (one command). Concerning the Numenera script, I removed the help.txt and added a link to the wiki page (which is fully detailed) in the description . Is it enough?
If it's ok, I'll add a wiki page for the cypher script and a link.

**Comment by SteveKoontz** [comment]
That sounds fine and the wiki looks good. Let me know when the cypher script is documented and I'll merge these in.

**Comment by NathaTerrien** [comment]
@SteveKoontz The cypher script is documented in a wiki page and the link has been added to the package.json file, in the description.
https://wiki.roll20.net/Script:Cypher_System_Sheet

**Pull request merged**
