### PR TITLE
First public commit

### PR DESCRIPTION
**Pull request by iantoon0**
First commit of 5E BattleMaster. Detailed description can be found in the README, or at https://github.com/iantoon0/5E-BattleMaster.

### CODE REVIEW

**Comment by iantoon0** [comment]
Just found a major error with the way I was attempting to select targets- I'm going to fix that and then try to commit the changes to this pull request. Sorry about that.

**Comment by iantoon0** [comment]
Should be fixed and ready for upload now. Thanks!

**Comment by wing-it** [comment]
We'd prefer not to have submodules here, could you please commit this directly? Thanks!

**Comment by iantoon0** [comment]
Should be a folder now.

**Pull request merged**
