### PR TITLE
Markov - Added multiple list and whisper support

### PR DESCRIPTION
**Pull request by Zenith-One**
* Added a feature which allows user to have names whispered to them.
* Added capability to generate multiple names from an arbitrary number of namesets.
* Added help flag to command
* Renamed READ.me to README.md to play nicely with GitHub
* Version bump

### CODE REVIEW

**Comment by Zenith-One** [comment]
Will do. Also need to fix a bug where the GM can't get whispers. This seems like a really silly thing to happen since that feature is probably the most useful to the GM.

**Comment by Zenith-One** [comment]
Hopefully I did the script.json thing correctly.

**Comment by Zenith-One** [comment]
Squashed my commits

**Comment by RyanNerd** [comment]
Looks good. The script.json looks correct. There are a few scripts that have multiple authors/contributors that list roll20userid:"id1, id2"  The Flight script is formatted this way. Thanks again for your contribution.

**Pull request merged**
