### PR TITLE
Initiative Tracker Plus - Added several new pieces of functionality.

### PR DESCRIPTION
**Pull request by jaculpiii**
Added the following functionality along with some minor bug fixes and miscellaneous code cleanup.
* 2020-11-23 - Updated initiative round indicator to have Play, Stop and Pause buttons instead of ? and ??
* 2020-11-23 - Changed references to Tracker Jacker to Initiative Tracker Plus.  I am doing this to differentiate the new and drastically changing codebase from Ken L.'s original codebase so users that are happy with OG Tracker Jacker can continue to use it without confusion.
* 2020-12-02 - Added a command to clear all statuses from a token.  `!itp -dispmultistatusconfig removeall` while the token(s) are selected, or a button appears on the edit message as well.
* 2020-12-02 - Some minor code cleanup to make it easier for me to work with.
* 2020-12-28 - Changed '? Round 1' (which changes to '?? Round 1' when paused) to use a play button image |> and pause button image || instead.
* 2021-02-13 - Added -setConfig functionality to modify various fields, flags and design variables.  These changes will be stored in the state so should continue between sessions.  Use detailed below.

### CODE REVIEW

**Review by dave-roll20 — CHANGES_REQUESTED** [review]
The structure of your scripts must be in a folder named with the version number specified in script.json. For example, if the version in script.json is set to 0.1 then the folder that contains your API script would be named 0.1.

roll20-api-scripts/InitiativeTrackerPlus/0.1/initiative_tracker_plus.js

**Comment by jaculpiii** [comment]
> 
> 
> The structure of your scripts must be in a folder named with the version number specified in script.json. For example, if the version in script.json is set to 0.1 then the folder that contains your API script would be named 0.1.
> 
> roll20-api-scripts/InitiativeTrackerPlus/0.1/initiative_tracker_plus.js

Should the initiative_tracker_plus.js be completely removed from the root directory as well?  I've pushed the changes to move the latest into a subdirectory named the same as the version.

**Comment by shdwjk** [comment]
The one in the root won't be used for any automation, but harms nothing by being there.  Personally, I always drop my latest version in the root for people who aren't using 1-click installs.

**Comment by jaculpiii** [comment]
> 
> 
> The one in the root won't be used for any automation, but harms nothing by being there. Personally, I always drop my latest version in the root for people who aren't using 1-click installs.

Perfect then I think I'm good, not sure how to mark this change as completed (I'm a novice at git) and I'm assuming it won't hit the one-click until next week's update.

Thanks again!
Chuz

**Pull request merged**
